<?php if (!defined('ABSPATH')) exit; ?>
<main class="alt-wrap alt-health-page" id="alt-health-page">
  <header class="alt-health-hero"><p class="alt-eyebrow">AskTheRecruiter · public operations</p><h1>AI Tracker Health</h1><p>Live collector health, evidence integrity, coverage limits and active quality work. A degraded source is a visible gap—not a zero result.</p><p id="alt-health-updated" role="status">Loading live operational status…</p></header>
  <section class="alt-health-summary" aria-label="Operational summary" id="alt-health-summary"></section>
  <section class="alt-health-section"><h2>Collector operations</h2><p>Last completed source attempt. Counts are raw candidate documents, not a claim of accepted events.</p><div class="alt-health-table-wrap"><table><thead><tr><th>Source</th><th>Coverage target</th><th>Cadence</th><th>Last pull</th><th>Result</th><th>Status / safe detail</th></tr></thead><tbody id="alt-health-sources"></tbody></table></div></section>
  <section class="alt-health-grid"><div class="alt-health-section"><h2>Current work</h2><div id="alt-health-workstreams"></div></div><div class="alt-health-section"><h2>Actionable backlogs</h2><div id="alt-health-backlogs"></div></div></section>
  <section class="alt-health-section"><h2>Schedule and coverage</h2><ul class="alt-health-schedule"><li><b>Railway, twice daily:</b> SEC EDGAR, NewsAPI, global GDELT and reviewed company IR feeds.</li><li><b>GitHub Actions, daily:</b> US WARN and Eurofound ERM at 13:00 UTC; dedupe, quality, evidence-hash and bounded enrichment/recovery jobs.</li><li><b>Monthly:</b> strict US Challenger reconciliation. A red threshold is a coverage alert, not a data-ingest crash.</li><li><b>Pending setup:</b> EDINET, OpenDART and Companies House access is verified, but no connector is claimed live until permitted and tested.</li></ul><p>Historical per-run volume telemetry begins with the health-dashboard release; legacy daily pull counts are not reconstructed or guessed.</p></section>
  <p class="alt-health-links">Machine-readable: <a href="<?php echo esc_url(rest_url('layoffs/v1/quality-status')); ?>">quality</a> · <a href="<?php echo esc_url(rest_url('layoffs/v1/integrity-status')); ?>">integrity</a> · <a href="<?php echo esc_url(rest_url('layoffs/v1/source-health')); ?>">source health</a> · <a href="<?php echo esc_url(rest_url('layoffs/v1/dataset-releases')); ?>">release ledger</a></p>
</main>
