<?php if (!defined('ABSPATH')) exit; ?>
<main class="alt-wrap alt-health-page" id="alt-health-page">
  <header class="alt-health-hero"><p class="alt-eyebrow">AskTheRecruiter · public operations</p><h1>AI Tracker Health</h1><p>Live collector health, evidence integrity, coverage limits and active quality work. A degraded source is a visible gap—not a zero result.</p><p id="alt-health-updated" role="status">Loading live operational status…</p></header>
  <section class="alt-health-summary" aria-label="Operational summary" id="alt-health-summary"></section>
  <section class="alt-health-grid"><div class="alt-health-section"><h2>Operator actions — needs a human, once</h2><ul class="alt-health-schedule">
    <li><b>Cloudflare cache rule</b> for <code>/blog/ai-layoff-tracker*</code> ("Eligible for cache") — cuts first paint from ~1.5s to ~200ms.</li>
    <li><b>Search Console:</b> submit <code>/blog/company-layoffs-sitemap.xml</code>.</li>
    <li><b>Denmark Jobindsats key:</b> send the drafted application (docs/outreach/); store as <code>JOBINDSATS_API_KEY_DK</code>.</li>
    <li><b>Quebec MESS courtesy notice:</b> send the drafted email; collector is pre-built.</li>
    <li><b>CourtListener token:</b> free signup; store as <code>COURTLISTENER_API_KEY</code>.</li>
    <li><b>Aggregator lead-access emails:</b> send the drafted permission requests to layoffs.fyi and TrueUp (docs/outreach/aggregator-lead-access.md) — unlocks automated daily lead checks; until a yes, aggregator monitoring stays manual by policy.</li>
  </ul></div>
  <div class="alt-health-section"><h2>Operate — for maintainers &amp; agents</h2><ul class="alt-health-schedule">
    <li><a href="https://github.com/dk-forge/ai-layoff-tracker/actions" target="_blank" rel="noopener">GitHub Actions</a> — every scheduled job, manual dispatches, full run logs.</li>
    <li><a href="https://github.com/dk-forge/ai-layoff-tracker/blob/main/docs/QUALITY_ROADMAP_HANDOVER.md" target="_blank" rel="noopener">Continuation brief</a> — the complete state of the programme for any new agent or maintainer.</li>
    <li><a href="https://github.com/dk-forge/ai-layoff-tracker/blob/main/docs/CHALLENGER_GAP_CLOSURE_PLAN.md" target="_blank" rel="noopener">Challenger gap-closure plan</a> — the ranked path to parity, with executed items marked.</li>
    <li><a href="<?php echo esc_url(rest_url('layoffs/v1/quality-status')); ?>">quality-status</a> · <a href="<?php echo esc_url(rest_url('layoffs/v1/integrity-status')); ?>">integrity-status</a> — machine-readable state for automation.</li>
  </ul></div></section>
  <section class="alt-health-section alt-feature-list" aria-labelledby="alt-feature-list-heading">
    <div class="alt-feature-list-heading"><div><p class="alt-eyebrow">Product roadmap</p><h2 id="alt-feature-list-heading">Features list</h2></div><p>Released capabilities and their rollout state. Live collector status and errors are shown above; this list does not imply complete country coverage.</p></div>
    <div class="alt-feature-grid">
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Source-linked event records</h3><p>Published events keep cited filings, government notices, company statements or named reports; canonical records can retain several reports.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Evidence-aware AI classification</h3><p>AI-primary, contributing, context and denial are kept separate. Model extraction assists; source quotes and deterministic checks decide publication.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Deduplication and lifecycle review</h3><p>Cross-outlet reports are merged into source-preserving canonical events. Possible announcement-to-execution matches enter a read-only editorial queue.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Public data and audit tools</h3><p>Filters, exports, record sources, corrections, release ledger, integrity, quality and source-health endpoints are publicly available.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Collector-run ledger</h3><p>Source attempts, raw candidate volumes and visible degraded states are retained from this release onward; no legacy run history is guessed.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Dataset releases and change report</h3><p>Each deployment snapshots the public dataset; this page reports the retained ledger window and disclosed recent corrections, removals, merges and coverage status.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>US Challenger comparison</h3><p>A monthly, like-for-like US employer / announcement / AI-primary comparator publishes the measured gap without changing tracker totals to match it.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>High-impact editorial review</h3><p>Very large, AI-primary and multi-country events are surfaced for source-based review; nothing is silently auto-corrected.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Durable evidence hashes</h3><p>Every retained excerpt is hashed: new excerpts at write time, and the legacy backlog completed its bounded backfill on July 18, 2026. Any newly pending hashes are reported live above.</p></article>
      <article><span class="alt-health-status alt-health-in_progress">In progress</span><h3>Announcement-date and employer-domicile enrichment</h3><p>Daily, evidence-only enrichment improves strict Challenger comparison eligibility. Unknown fields remain blank rather than inferred.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Measured country recall</h3><p>The first published sample: California WARN, June 2026 — 11 of 12 independently transcribed official notices matched a canonical tracker event (91.7% sample recall), measured through a three-actor review chain against a sealed official document. A sample is a spot measurement, never a completeness claim; further country-period samples follow the same protocol.</p></article>
      <article><span class="alt-health-status alt-health-pending_permission">Pending review</span><h3>Official national and company IR connectors</h3><p>The first five reviewed company-owned IR feeds (Intel, SAP, Cisco, Salesforce, Micron) were admitted to the versioned registry on July 18, 2026. Japan EDINET and South Korea OpenDART discovery probes now run on the twice-daily schedule and report health above — they list official filings only and ingest nothing. A country is claimed covered only after an evidence-gated extraction connector passes review.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Embeddable US widgets</h3><p>A noindex, source-linked US national/state iframe widget links readers to its exact filtered tracker view. Build copyable code on the <a href="<?php echo esc_url(home_url('/ai-layoff-tracker/publisher-tools/')); ?>">publisher tools page</a>; metro variants remain deliberately out of scope.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Company layoff directory</h3><p>Pages live at /company-layoffs/ and grow automatically: a weekly autopilot admits companies with three or more source-linked canonical events and a clean identity, validated by the same server rules as manual review. Indexable pages are listed in the sitemap; below-threshold pages stay noindex.</p></article>
      <article><span class="alt-health-status alt-health-active">Active</span><h3>Quarterly State of Layoffs report</h3><p>The query-backed HTML report is published from an immutable server-generated snapshot, with its data revision and coverage limits disclosed.</p></article>
      <article><span class="alt-health-status alt-health-in_progress">In progress</span><h3>WARN transparency dataset</h3><p>The separate evidence-linked research foundation is ready. It will not label an employer non-compliant without verified notice, timing and adjudication evidence.</p></article>
    </div>
  </section>
  <section class="alt-health-section"><h2>Collector operations</h2><p>Last completed source attempt. Counts are raw candidate documents, not a claim of accepted events.</p><div class="alt-health-table-wrap"><table><thead><tr><th>Source</th><th>Coverage target</th><th>Cadence</th><th>Last pull</th><th>Result</th><th>Status / safe detail</th></tr></thead><tbody id="alt-health-sources"></tbody></table></div></section>
  <section class="alt-health-section"><div class="alt-health-run-heading"><div><h2>Recent collector runs</h2><p>Append-only history from this health-ledger release onward. It records source attempts and raw candidates—not accepted events—and never reconstructs earlier runs.</p></div><label for="alt-health-run-days">Window <select id="alt-health-run-days"><option value="7">Last 7 days</option><option value="30" selected>Last 30 days</option><option value="90">Last 90 days</option></select></label></div><div class="alt-health-table-wrap"><table><thead><tr><th>When</th><th>Source</th><th>Status</th><th>Raw candidates</th><th>Safe detail</th></tr></thead><tbody id="alt-health-runs"></tbody></table></div></section>
  <section class="alt-health-grid"><div class="alt-health-section"><h2>Current work</h2><div id="alt-health-workstreams"></div></div><div class="alt-health-section"><h2>Actionable backlogs</h2><div id="alt-health-backlogs"></div></div></section>
  <section class="alt-health-section"><h2>Schedule and coverage</h2><ul class="alt-health-schedule"><li><b>Railway, twice daily:</b> SEC EDGAR (United States), NewsAPI and global GDELT (worldwide news), reviewed company IR feeds, plus Japan EDINET and South Korea OpenDART discovery probes (official filing lists only — nothing is ingested or classified from them).</li><li><b>GitHub Actions, daily:</b> US WARN and Eurofound ERM (European Union) at 13:00 UTC; dedupe, quality, evidence-hash and bounded enrichment/recovery jobs.</li><li><b>Monthly:</b> strict US Challenger reconciliation. A red threshold is a coverage alert, not a data-ingest crash.</li><li><b>Discovery only:</b> the Japan and South Korea probes report their run health above but are not a coverage claim; an evidence-gated extraction connector must pass review first. United Kingdom Companies House access is identity-support only.</li></ul><p>Collector-run telemetry begins with plugin 2.18.21; legacy daily pull counts are not reconstructed or guessed.</p></section>
  <section class="alt-health-section"><h2>Benchmark race — Challenger &amp; layoffs.fyi vs ATR</h2>
    <p>Our cells recompute from the live database on every page load, so each data pull moves this table. Challenger cells update automatically when the monthly reconciliation stores their new report. layoffs.fyi cells are manually verified snapshots (leads-only policy; no automated pulls without their permission) with the as-of date shown.</p>
    <div class="alt-health-table-wrap"><table>
      <thead><tr><th>Measure (2026)</th><th>Challenger</th><th>layoffs.fyi</th><th>ATR (live)</th><th>ATR vs benchmark</th></tr></thead>
      <tbody id="alt-bench-race"><tr><td colspan="5">Loading live benchmark comparison…</td></tr></tbody>
    </table></div>
  </section>
  <section class="alt-health-section"><h2>Rolling dataset change report</h2><p>Snapshot totals begin at ledger inception. Net change is not labelled as gross additions, because merges, corrections and removals can change the total.</p><div id="alt-health-release-report" aria-live="polite">Loading release and change data…</div></section>
  <p class="alt-health-links">Machine-readable: <a href="<?php echo esc_url(rest_url('layoffs/v1/quality-status')); ?>">quality</a> · <a href="<?php echo esc_url(rest_url('layoffs/v1/integrity-status')); ?>">integrity</a> · <a href="<?php echo esc_url(rest_url('layoffs/v1/source-health')); ?>">source health</a> · <a href="<?php echo esc_url(rest_url('layoffs/v1/source-runs')); ?>">collector runs</a> · <a href="<?php echo esc_url(rest_url('layoffs/v1/dataset-releases')); ?>">release ledger</a></p>
</main>
