"""The public "we scan N countries" figure must count countries only.

The number on the tracker and the sources page is generated by
railway/generate_country_table.py, which reads the collector's own allowlist
comments in sources/gdelt.py. Those comments label the US metro block with the
OUTLET or the STATE ("# Tampa Bay Times", "# Oklahoma - Tulsa World"), and for
months each of those became a country row: the public figure read 203 when the
honest answer was 180 (21 US metro outlets and US states, plus 2 grouping
rows), an 11 percent overcount on a number journalists quote.

This test exists so that can never come back. It fails if a US state or a US
metro outlet is ever counted as a country, if any counted row is not a real
country or territory, or if the committed partials drift from the generator.
"""
import os
import re
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))

import generate_country_table as gct  # noqa: E402

PARTIALS = os.path.normpath(os.path.join(
    HERE, "..", "..", "wordpress-plugin", "ai-layoff-tracker",
    "templates", "partials"))

# Georgia is both a US state and a country; the allowlist's Georgia rows are
# .ge domains, so the country wins there and it is not evidence of the bug.
US_ONLY_STATES = gct.US_STATE_NAMES - set(gct.COUNTRIES)


def _read(name):
    with open(os.path.join(PARTIALS, name), encoding="utf-8") as fh:
        return fh.read()


class CountryCountCountsCountriesOnly(unittest.TestCase):

    def setUp(self):
        self.rows = gct.parse()

    def test_no_us_state_is_a_row(self):
        offenders = sorted(set(self.rows) & US_ONLY_STATES)
        self.assertEqual([], offenders,
                         "US states rendered as country rows: %s" % offenders)

    def test_no_us_metro_outlet_is_a_row(self):
        offenders = sorted(set(self.rows) & gct.US_LOCAL_LABELS)
        self.assertEqual([], offenders,
                         "US metro outlets rendered as country rows: %s" % offenders)

    def test_every_counted_row_is_a_real_country(self):
        counted = [c for c in self.rows if gct.classify(c)[1]]
        strays = sorted(c for c in counted if c not in gct.COUNTRIES)
        self.assertEqual([], strays,
                         "counted as countries but not in COUNTRIES: %s" % strays)

    def test_grouping_rows_are_listed_but_not_counted(self):
        # They are real rows on the page (the reader should see them) and they
        # are not places, so they must never reach the count.
        for label in ("EU-wide", gct.CATCH_ALL):
            self.assertIn(label, self.rows)
            self.assertFalse(gct.classify(label)[1], label)

    def test_count_is_smaller_than_the_row_count(self):
        # Sanity: if these ever match, the grouping rows are being counted.
        self.assertLess(gct.country_count(self.rows), len(self.rows))

    def test_a_us_state_label_can_never_raise_the_count(self):
        # Direct guard on the classifier, independent of today's allowlist.
        for label in sorted(US_ONLY_STATES) + sorted(gct.US_LOCAL_LABELS):
            row, counts = gct.classify(label)
            self.assertEqual("United States", row, label)
            self.assertTrue(counts, label)   # folded in, never its own country

    def test_scan_scope_partial_matches_the_generator(self):
        scope = _read("scan-scope.php")
        m = re.search(r"\$alt_scan_countries\s*=\s*(\d+)", scope)
        self.assertIsNotNone(m, "scan-scope.php has no $alt_scan_countries")
        self.assertEqual(gct.country_count(self.rows), int(m.group(1)),
                         "scan-scope.php is stale: re-run "
                         "python3 railway/generate_country_table.py")
        o = re.search(r"\$alt_scan_outlets\s*=\s*(\d+)", scope)
        self.assertIsNotNone(o)
        self.assertEqual(sum(len(v) for v in self.rows.values()), int(o.group(1)))

    def test_country_table_summary_matches_the_generator(self):
        table = _read("country-sources-table.php")
        m = re.search(r"we scan \((\d+) countries, (\d+) outlets\)", table)
        self.assertIsNotNone(m, "country-sources-table.php summary changed shape")
        self.assertEqual(gct.country_count(self.rows), int(m.group(1)),
                         "country-sources-table.php is stale: re-run "
                         "python3 railway/generate_country_table.py")

    def test_table_names_no_retired_collector(self):
        # NewsAPI is dead and replaced by Google News; the generated copy used
        # to name it, and the committed partial had been hand-corrected, which
        # is exactly the drift a regeneration would have silently undone.
        table = _read("country-sources-table.php")
        self.assertNotIn("NewsAPI", table)
        self.assertIn("Google News", table)


if __name__ == "__main__":
    unittest.main()
