#!/usr/bin/env python3
"""Generate a SYNTHETIC wp_alt_layoffs snapshot for a throwaway test DB.

Emits a .sql file (CREATE TABLE + INSERTs) with the columns /aggregate and
/query read, filled with random-but-realistic fake rows. NEVER a copy of
production — no real companies, no PII — so it's safe to run anywhere. Purpose:
a session can load this, run the OLD vs NEW aggregate SQL against it, and prove
the numbers are byte-identical before shipping a query rewrite.

    python3 railway/gen_synthetic_snapshot.py --rows 20000 --out synthetic_snapshot.sql
    bash scripts/setup_test_db.sh   # loads it into MySQL `alt_test`
"""
import argparse
import random

INDUSTRIES = ["Technology", "Manufacturing", "Finance & Insurance", "Retail & E-commerce",
              "Healthcare & Pharma", "Automotive", "Logistics & Transport", "Media & Entertainment",
              "Government & Nonprofit", "Telecom", "Energy", "Airlines & Travel", ""]
COUNTRIES = (["United States"] * 60 + ["Multiple countries"] * 8 + ["Germany", "United Kingdom",
             "Canada", "France", "India", "Japan", "Australia", "Spain", "Italy", "Netherlands"] * 3)
US_STATES = ["CA", "TX", "NY", "WA", "FL", "IL", "MA", "GA", "MI", "OH", "NJ", "PA", "NC", ""]
SOURCE_TYPES = (["warn"] * 55 + ["news"] * 35 + ["8K"] * 5 + ["erm"] * 5)
VERIF = {"warn": "warn", "news": "bronze", "8K": "gold", "erm": "silver"}
REASON_TAGS = ["", "restructuring", "cost_reduction", "ai_automation", "possible_ai",
               "revenue_decline", "closure", "macroeconomic"]
AI_CAUS = ["", "primary_cause", "contributing", "ai_linked", "unknown"]


def _rows(n, seed):
    rnd = random.Random(seed)
    out = []
    for i in range(1, n + 1):
        st = rnd.choice(SOURCE_TYPES)
        country = rnd.choice(COUNTRIES)
        is_us = country == "United States"
        emp_country = country if country != "Multiple countries" else rnd.choice(["United States", "Germany", "United Kingdom"])
        year = rnd.choices([2024, 2025, 2026], weights=[1, 2, 4])[0]
        month = rnd.randint(1, 12 if year < 2026 else 7)
        day = rnd.randint(1, 28)
        jc = rnd.choice([rnd.randint(20, 200), rnd.randint(50, 500), rnd.randint(200, 5000), rnd.randint(1000, 25000)])
        ai_explicit = 1 if (st in ("news", "8K") and rnd.random() < 0.10) else 0
        tag = rnd.choice(REASON_TAGS) if st != "warn" else ""
        if ai_explicit and tag not in ("ai_automation", "possible_ai"):
            tag = rnd.choice(["ai_automation", "possible_ai"])
        company = f"Synthetic Co {rnd.randint(1, 4000)}"
        out.append((
            i, company, company.lower().replace(" ", ""), jc,
            f"{year}-{month:02d}-{day:02d}", country, emp_country,
            (rnd.choice(US_STATES) if is_us else ""), rnd.choice(INDUSTRIES),
            st, VERIF[st], ai_explicit, (rnd.choice(AI_CAUS) if ai_explicit else ""),
            tag,
        ))
    return out


DDL = """DROP TABLE IF EXISTS wp_alt_layoffs;
CREATE TABLE wp_alt_layoffs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company VARCHAR(255) NOT NULL DEFAULT '',
  company_key VARCHAR(255) NOT NULL DEFAULT '',
  job_count INT UNSIGNED NOT NULL DEFAULT 0,
  layoff_date DATE DEFAULT NULL,
  country VARCHAR(64) NOT NULL DEFAULT '',
  employer_country VARCHAR(64) NOT NULL DEFAULT '',
  state VARCHAR(8) NOT NULL DEFAULT '',
  industry VARCHAR(64) NOT NULL DEFAULT '',
  source_type VARCHAR(32) NOT NULL DEFAULT '',
  verification_level VARCHAR(32) NOT NULL DEFAULT '',
  ai_explicit TINYINT(1) NOT NULL DEFAULT 0,
  ai_causation VARCHAR(32) NOT NULL DEFAULT '',
  reason_tags VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  KEY layoff_date (layoff_date),
  KEY country (country),
  KEY source_type (source_type),
  KEY ai_explicit (ai_explicit)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rows", type=int, default=20000)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--out", default="synthetic_snapshot.sql")
    a = ap.parse_args()
    rows = _rows(a.rows, a.seed)
    with open(a.out, "w") as f:
        f.write("-- SYNTHETIC test data — not production. Generated by gen_synthetic_snapshot.py\n")
        f.write(DDL)
        cols = "(company,company_key,job_count,layoff_date,country,employer_country,state,industry,source_type,verification_level,ai_explicit,ai_causation,reason_tags)"
        for batch_start in range(0, len(rows), 500):
            chunk = rows[batch_start:batch_start + 500]
            vals = ",".join(
                "('{}','{}',{},'{}','{}','{}','{}','{}','{}','{}',{},'{}','{}')".format(
                    r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9], r[10], r[11], r[12], r[13])
                for r in chunk)
            f.write(f"INSERT INTO wp_alt_layoffs {cols} VALUES {vals};\n")
    print(f"wrote {len(rows)} synthetic rows to {a.out}")


if __name__ == "__main__":
    main()
