"""Generate the plugin's PHP copy of the official state WARN list URLs.

`railway/sources/warn.py::STATE_WARN_URL` is the single source of truth (it is
what the importer stamps onto list-only notices). The tracker front-end needs
the same map at render time so it can show a row's state WARN LIST link even
when `source_url` already points at an exact per-notice page. Rather than keep
a hand-maintained second copy in PHP (which drifts), we generate the partial
from the Python map. `tests/test_warn_url_parity.py` fails if they diverge.

Run after editing STATE_WARN_URL:
    python generate_warn_urls.py
"""
import os

from sources.warn import STATE_WARN_URL

OUT = os.path.join(
    os.path.dirname(__file__), "..", "wordpress-plugin", "ai-layoff-tracker",
    "templates", "partials", "warn-state-urls.php",
)


def render_php(mapping):
    lines = [
        "<?php",
        "/**",
        " * GENERATED by railway/generate_warn_urls.py from",
        " * railway/sources/warn.py::STATE_WARN_URL. Do not edit by hand;",
        " * edit the Python map and re-run the generator (a parity test enforces it).",
        " *",
        " * Official state WARN program / database page per state. Used to show the",
        " * 'State WARN list' link beside a notice's exact-record link.",
        " */",
        "if (!defined('ABSPATH')) exit;",
        "",
        "function alt_state_warn_urls() {",
        "    return array(",
    ]
    for st in sorted(mapping):
        url = mapping[st].replace("'", "\\'")
        lines.append(f"        '{st}' => '{url}',")
    lines += [
        "    );",
        "}",
        "",
        "function alt_state_warn_list_url($state) {",
        "    $map = alt_state_warn_urls();",
        "    $state = strtoupper(trim((string) $state));",
        "    return isset($map[$state]) ? $map[$state] : '';",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    php = render_php(STATE_WARN_URL)
    with open(os.path.abspath(OUT), "w", encoding="utf-8") as fh:
        fh.write(php)
    print(f"Wrote {len(STATE_WARN_URL)} state WARN URLs to {os.path.abspath(OUT)}")


if __name__ == "__main__":
    main()
