"""Generate the health page's per-country source table from the code itself.

Parses TRUSTED_DOMAINS entries in sources/gdelt.py (domain + country comment)
and emits a static PHP partial, so the public table can never drift from what
the collector actually scans. Re-run after allowlist changes:

    python3 generate_country_table.py
"""
import re
from collections import OrderedDict
from pathlib import Path

SRC = Path(__file__).parent / "sources" / "gdelt.py"
OUT = Path(__file__).parent.parent / "wordpress-plugin" / "ai-layoff-tracker" / "templates" / "partials" / "country-sources-table.php"

OFFICIAL = {
    "United States": "SEC EDGAR 8-K/6-K incl. Item 2.05 (2×/day) · WARN notices, 44 jurisdictions (daily)",
    "European Union": "Eurofound ERM restructuring monitor (daily)",
    "United Kingdom": "Companies House identity checks (on demand); LSE RNS pending licence",
    "Japan": "EDINET discovery probe, 2×/day (list-only)",
    "South Korea": "OpenDART discovery probe, 2×/day (list-only)",
    "Canada": "Quebec collective-dismissal lists: candidate (courtesy notice pending)",
    "Brazil": "CVM filings index: discovery client built, pending promotion",
    "Denmark": "Jobindsats varsel API: key application pending",
}

# Countries whose news scanning ALSO rides Eurofound ERM coverage.
EU = {"Germany", "France", "Spain", "Italy", "Netherlands", "Belgium", "Sweden",
      "Denmark", "Norway", "Finland", "Ireland", "Poland", "Austria", "Portugal",
      "Greece", "Czech Republic", "Czechia", "Hungary", "Romania", "Bulgaria",
      "Croatia", "Slovakia", "Slovenia", "Lithuania", "Latvia", "Estonia",
      "Luxembourg", "Malta", "Cyprus"}

COUNTRY_FIXES = {
    "Cote d'Ivoire": "Côte d'Ivoire", "DR Congo": "DR Congo",
    "Congo-Brazzaville": "Congo (Brazzaville)", "Central African Rep.": "Central African Republic",
}


def parse():
    countries = OrderedDict()
    text = SRC.read_text()
    body = text.split("TRUSTED_DOMAINS = {", 1)[1].split("\n}", 1)[0]
    for line in body.splitlines():
        m = re.match(r'\s*((?:"[a-z0-9.\-]+",\s*)+)#\s*(.+)$', line)
        if not m:
            continue
        domains = re.findall(r'"([a-z0-9.\-]+)"', m.group(1))
        comment = m.group(2).strip()
        # Worldwide-block style: "Country — Outlet (note)"; legacy style: "Country"
        country = re.split(r"\s+[—-]\s+", comment, 1)[0].strip()
        country = re.sub(r"\s*\(.*\)$", "", country)
        stop = {"npr", "network", "daily", "dailies", "news", "business", "wire",
                "wires", "trade", "tv", "press", "journal", "radio", "regional",
                "national", "general", "tech", "finance", "metro", "coverage",
                "outlets", "more", "dupes", "harmless", "english", "paywalled",
                "acbj", "sibling", "banner", "tribune", "gulf", "nordics", "crain's"}
        words = country.split()
        if (not re.match(r"^[A-ZÀ-Ü]", country) or len(words) > 3
                or any(w.strip("().,'&—-").lower() in stop for w in words)):
            country = "United States & global English press"
        if "/" in country and country not in ("Russia / Ukraine", "Mexico / Argentina"):
            country = country.split("/")[0].strip()
        country = COUNTRY_FIXES.get(country, country)
        for splitter in (" / ",):
            if splitter in country:
                country = country.split(splitter)[0].strip()
        countries.setdefault(country, [])
        for d in domains:
            if d not in countries[country]:
                countries[country].append(d)
    return countries


def render(countries):
    rows = []
    for country in sorted(countries, key=lambda c: (c == "United States & global English press", c)):
        outlets = countries[country]
        official = OFFICIAL.get(country, "")
        if not official and country in EU:
            official = "Eurofound ERM (EU-wide, daily)"
        if not official:
            official = "— (no permitted public register; see research docs)"
        rows.append(
            "<tr><th>{c}</th><td>{o}</td><td>{n}</td>"
            "<td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>".format(
                c=country, o=official,
                n=", ".join(outlets[:14]) + (" +{} more".format(len(outlets) - 14) if len(outlets) > 14 else "")))
    return (
        "<?php if (!defined('ABSPATH')) exit; // GENERATED by railway/generate_country_table.py — do not hand-edit ?>\n"
        "<details class=\"alt-health-section\"><summary><b>Every country and every outlet we scan ({n} countries, {d} outlets)</b> — generated from the collector's own allowlist</summary>"
        "<div class=\"alt-health-table-wrap\"><table><thead><tr><th>Country</th><th>Official sources</th><th>News outlets scanned (via GDELT Translingual + NewsAPI)</th><th>News scan status</th></tr></thead><tbody>\n"
        .format(n=len(countries), d=sum(len(v) for v in countries.values()))
        + "\n".join(rows)
        + "\n</tbody></table></div><p>Outlet scanning is allowlist-only: articles surface through GDELT's 65-language index and NewsAPI; sites are never crawled directly. Rotating country/state/industry queries sweep the full matrix every ~6–9 days on top of the broad twice-daily pull.</p></details>\n")


if __name__ == "__main__":
    countries = parse()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(countries))
    print(f"wrote {OUT} — {len(countries)} countries, {sum(len(v) for v in countries.values())} outlets")
