<?php if (!defined('ABSPATH')) exit; // GENERATED by railway/generate_country_table.py — do not hand-edit ?>
<details class="alt-health-section"><summary><b>Every country and every outlet we scan (188 countries, 466 outlets)</b> — generated from the collector's own allowlist</summary><div class="alt-health-table-wrap"><table><thead><tr><th>Country</th><th>Official sources</th><th>News outlets scanned (via GDELT Translingual + NewsAPI)</th><th>News scan status</th></tr></thead><tbody>
<tr><th>APM Marketplace</th><td>— (no permitted public register; see research docs)</td><td>marketplace.org</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Afghanistan</th><td>— (no permitted public register; see research docs)</td><td>tolonews.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Albania</th><td>— (no permitted public register; see research docs)</td><td>panorama.com.al, monitor.al</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Algeria</th><td>— (no permitted public register; see research docs)</td><td>elwatan-dz.com, elkhabar.com, tsa-algerie.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Antigua & Barbuda</th><td>— (no permitted public register; see research docs)</td><td>antiguaobserver.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Argentina</th><td>— (no permitted public register; see research docs)</td><td>ambito.com, cronista.com, lanacion.com.ar, infobae.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Arizona Republic</th><td>— (no permitted public register; see research docs)</td><td>azcentral.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Armenia</th><td>— (no permitted public register; see research docs)</td><td>civilnet.am, hetq.am</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Atlanta Journal-Constitution</th><td>— (no permitted public register; see research docs)</td><td>ajc.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Austin</th><td>— (no permitted public register; see research docs)</td><td>statesman.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Australia</th><td>— (no permitted public register; see research docs)</td><td>afr.com, theaustralian.com.au, news.com.au, theage.com.au, thewest.com.au, canberratimes.com.au, smartcompany.com.au</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Austria</th><td>Eurofound ERM (EU-wide, daily)</td><td>derstandard.at, diepresse.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Bahamas</th><td>— (no permitted public register; see research docs)</td><td>tribune242.com, thenassauguardian.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Bahrain</th><td>— (no permitted public register; see research docs)</td><td>gdnonline.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Bangladesh</th><td>— (no permitted public register; see research docs)</td><td>thedailystar.net, tbsnews.net, prothomalo.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Barbados</th><td>— (no permitted public register; see research docs)</td><td>nationnews.com, barbadostoday.bb</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Belarus</th><td>— (no permitted public register; see research docs)</td><td>zerkalo.io, nashaniva.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Belgium</th><td>Eurofound ERM (EU-wide, daily)</td><td>lesoir.be, standaard.be, tijd.be, lecho.be</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Belize</th><td>— (no permitted public register; see research docs)</td><td>amandala.com.bz</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Benin</th><td>— (no permitted public register; see research docs)</td><td>lanouvelletribune.info</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Bermuda</th><td>— (no permitted public register; see research docs)</td><td>royalgazette.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Bhutan</th><td>— (no permitted public register; see research docs)</td><td>kuenselonline.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Bolivia</th><td>— (no permitted public register; see research docs)</td><td>eldeber.com.bo, lostiempos.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Bosnia</th><td>— (no permitted public register; see research docs)</td><td>klix.ba, oslobodjenje.ba, n1info.ba</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Boston Globe Media</th><td>— (no permitted public register; see research docs)</td><td>boston.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Brazil</th><td>CVM filings index: discovery client built, pending promotion</td><td>globo.com, estadao.com.br, folha.uol.com.br, exame.com, infomoney.com.br</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Brunei</th><td>— (no permitted public register; see research docs)</td><td>borneobulletin.com.bn</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Bulgaria</th><td>Eurofound ERM (EU-wide, daily)</td><td>capital.bg, dnevnik.bg</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Burkina Faso</th><td>— (no permitted public register; see research docs)</td><td>lefaso.net</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Burundi</th><td>— (no permitted public register; see research docs)</td><td>iwacu-burundi.org</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Cambodia</th><td>— (no permitted public register; see research docs)</td><td>kiripost.com, khmertimeskh.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Cameroon</th><td>— (no permitted public register; see research docs)</td><td>businessincameroon.com, journalducameroun.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Canada</th><td>Quebec collective-dismissal lists: candidate (courtesy notice pending)</td><td>lapresse.ca, lesaffaires.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Cape Verde</th><td>— (no permitted public register; see research docs)</td><td>expressodasilhas.cv</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Cayman Islands</th><td>— (no permitted public register; see research docs)</td><td>caymancompass.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Central African Republic</th><td>— (no permitted public register; see research docs)</td><td>radiondekeluka.org</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Chad</th><td>— (no permitted public register; see research docs)</td><td>tchadinfos.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Charlotte</th><td>— (no permitted public register; see research docs)</td><td>charlotteobserver.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Chile</th><td>— (no permitted public register; see research docs)</td><td>df.cl, latercera.com, emol.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>China</th><td>— (no permitted public register; see research docs)</td><td>caixin.com, caixinglobal.com, yicai.com, yicaiglobal.com, jiemian.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Colombia</th><td>— (no permitted public register; see research docs)</td><td>eltiempo.com, portafolio.co, larepublica.co, elespectador.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Columbus Dispatch</th><td>— (no permitted public register; see research docs)</td><td>dispatch.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Congo (Brazzaville)</th><td>— (no permitted public register; see research docs)</td><td>adiac-congo.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Cook Islands</th><td>— (no permitted public register; see research docs)</td><td>cookislandsnews.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Costa Rica</th><td>— (no permitted public register; see research docs)</td><td>nacion.com, elfinancierocr.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Croatia</th><td>Eurofound ERM (EU-wide, daily)</td><td>jutarnji.hr, poslovni.hr, n1info.hr</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Cuba</th><td>— (no permitted public register; see research docs)</td><td>14ymedio.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Curaçao</th><td>— (no permitted public register; see research docs)</td><td>antilliaansdagblad.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Cyprus</th><td>Eurofound ERM (EU-wide, daily)</td><td>cyprus-mail.com, philenews.com, stockwatch.com.cy</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Czechia</th><td>Eurofound ERM (EU-wide, daily)</td><td>hn.cz, denikn.cz, seznamzpravy.cz</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Côte d'Ivoire</th><td>— (no permitted public register; see research docs)</td><td>fratmat.info, sikafinance.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>DR Congo</th><td>— (no permitted public register; see research docs)</td><td>actualite.cd, radiookapi.net</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Denmark</th><td>Jobindsats varsel API: key application pending</td><td>politiken.dk, borsen.dk, berlingske.dk</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Dominica</th><td>— (no permitted public register; see research docs)</td><td>dominicanewsonline.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Dominican Republic</th><td>— (no permitted public register; see research docs)</td><td>listindiario.com, diariolibre.com, eldinero.com.do</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>EU-wide</th><td>— (no permitted public register; see research docs)</td><td>euronews.com, politico.eu, euractiv.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Ecuador</th><td>— (no permitted public register; see research docs)</td><td>eluniverso.com, primicias.ec</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Egypt</th><td>— (no permitted public register; see research docs)</td><td>ahram.org.eg, dailynewsegypt.com, almasryalyoum.com, enterprise.press</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>El Salvador</th><td>— (no permitted public register; see research docs)</td><td>laprensagrafica.com, elsalvador.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Estonia</th><td>Eurofound ERM (EU-wide, daily)</td><td>postimees.ee, err.ee, aripaev.ee</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Ethiopia</th><td>— (no permitted public register; see research docs)</td><td>addisfortune.news, thereporterethiopia.com, addisstandard.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Fiji</th><td>— (no permitted public register; see research docs)</td><td>fijitimes.com.fj, fijivillage.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Finland</th><td>Eurofound ERM (EU-wide, daily)</td><td>helsinkitimes.fi, hs.fi, kauppalehti.fi</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>France</th><td>Eurofound ERM (EU-wide, daily)</td><td>lemonde.fr, lesechos.fr, lefigaro.fr, liberation.fr, lexpress.fr, latribune.fr</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>French Polynesia</th><td>— (no permitted public register; see research docs)</td><td>tahiti-infos.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Gabon</th><td>— (no permitted public register; see research docs)</td><td>gabonreview.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Gambia</th><td>— (no permitted public register; see research docs)</td><td>thepoint.gm</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Georgia</th><td>— (no permitted public register; see research docs)</td><td>civil.ge, bm.ge</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Germany</th><td>Eurofound ERM (EU-wide, daily)</td><td>handelsblatt.com, spiegel.de, faz.net, zeit.de, sueddeutsche.de, welt.de, tagesschau.de</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Ghana</th><td>— (no permitted public register; see research docs)</td><td>graphic.com.gh, myjoyonline.com, thebftonline.com, citinewsroom.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Greece</th><td>Eurofound ERM (EU-wide, daily)</td><td>kathimerini.gr, ekathimerini.com, naftemporiki.gr</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Greenfield Recorder</th><td>— (no permitted public register; see research docs)</td><td>recorder.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Grenada</th><td>— (no permitted public register; see research docs)</td><td>nowgrenada.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Guam</th><td>— (no permitted public register; see research docs)</td><td>guampdn.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Guatemala</th><td>— (no permitted public register; see research docs)</td><td>prensalibre.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Guinea</th><td>— (no permitted public register; see research docs)</td><td>guineenews.org</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Guyana</th><td>— (no permitted public register; see research docs)</td><td>stabroeknews.com, kaieteurnewsonline.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Haiti</th><td>— (no permitted public register; see research docs)</td><td>lenouvelliste.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Honduras</th><td>— (no permitted public register; see research docs)</td><td>laprensa.hn, elheraldo.hn</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Hong Kong</th><td>— (no permitted public register; see research docs)</td><td>hket.com, mingpao.com, thestandard.com.hk</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Hungary</th><td>Eurofound ERM (EU-wide, daily)</td><td>portfolio.hu, hvg.hu, telex.hu</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Iceland</th><td>— (no permitted public register; see research docs)</td><td>mbl.is, visir.is</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>India</th><td>— (no permitted public register; see research docs)</td><td>indianexpress.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Indonesia</th><td>— (no permitted public register; see research docs)</td><td>thejakartapost.com, kompas.com, bisnis.com, kontan.co.id, tempo.co</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Iran</th><td>— (no permitted public register; see research docs)</td><td>donya-e-eqtesad.com, financialtribune.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Iraq</th><td>— (no permitted public register; see research docs)</td><td>rudaw.net, shafaq.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Ireland</th><td>Eurofound ERM (EU-wide, daily)</td><td>independent.ie, rte.ie, thejournal.ie</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Israel</th><td>— (no permitted public register; see research docs)</td><td>haaretz.com, timesofisrael.com, calcalistech.com, globes.co.il</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Italy</th><td>Eurofound ERM (EU-wide, daily)</td><td>corriere.it, ilsole24ore.com, repubblica.it, lastampa.it</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Jamaica</th><td>— (no permitted public register; see research docs)</td><td>jamaica-gleaner.com, jamaicaobserver.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Japan</th><td>EDINET discovery probe, 2×/day (list-only)</td><td>nikkei.com, asahi.com, yomiuri.co.jp, mainichi.jp</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Jordan</th><td>— (no permitted public register; see research docs)</td><td>jordantimes.com, alghad.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Kenya</th><td>— (no permitted public register; see research docs)</td><td>nation.africa, businessdailyafrica.com, standardmedia.co.ke, theeastafrican.co.ke</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Kosovo</th><td>— (no permitted public register; see research docs)</td><td>koha.net, prishtinainsight.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Kuwait</th><td>— (no permitted public register; see research docs)</td><td>kuwaittimes.com, alqabas.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Laos</th><td>— (no permitted public register; see research docs)</td><td>laotiantimes.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Las Vegas R-J</th><td>— (no permitted public register; see research docs)</td><td>reviewjournal.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Latvia</th><td>Eurofound ERM (EU-wide, daily)</td><td>lsm.lv, delfi.lv, db.lv</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Lebanon</th><td>— (no permitted public register; see research docs)</td><td>lorientlejour.com, annahar.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Liberia</th><td>— (no permitted public register; see research docs)</td><td>frontpageafricaonline.com, liberianobserver.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Libya</th><td>— (no permitted public register; see research docs)</td><td>libyaherald.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Lithuania</th><td>Eurofound ERM (EU-wide, daily)</td><td>lrt.lt, vz.lt, delfi.lt, 15min.lt</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Luxembourg</th><td>Eurofound ERM (EU-wide, daily)</td><td>luxtimes.lu, paperjam.lu</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Madagascar</th><td>— (no permitted public register; see research docs)</td><td>lexpress.mg, midi-madagasikara.mg</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Malaysia</th><td>— (no permitted public register; see research docs)</td><td>thestar.com.my, nst.com.my, theedgemalaysia.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Maldives</th><td>— (no permitted public register; see research docs)</td><td>mihaaru.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Mali</th><td>— (no permitted public register; see research docs)</td><td>journaldumali.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Malta</th><td>Eurofound ERM (EU-wide, daily)</td><td>timesofmalta.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Mauritania</th><td>— (no permitted public register; see research docs)</td><td>alakhbar.info</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Mauritius</th><td>— (no permitted public register; see research docs)</td><td>lexpress.mu, defimedia.info</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Mexico</th><td>— (no permitted public register; see research docs)</td><td>eleconomista.com.mx, clarin.com, elfinanciero.com.mx, eluniversal.com.mx, reforma.com, expansion.mx</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Moldova</th><td>— (no permitted public register; see research docs)</td><td>newsmaker.md, zdg.md, mold-street.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Mongolia</th><td>— (no permitted public register; see research docs)</td><td>news.mn, ikon.mn</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Montenegro</th><td>— (no permitted public register; see research docs)</td><td>vijesti.me</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Morocco</th><td>— (no permitted public register; see research docs)</td><td>leconomiste.com, medias24.com, hespress.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Myanmar</th><td>— (no permitted public register; see research docs)</td><td>irrawaddy.com, frontiermyanmar.net</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Nashville</th><td>— (no permitted public register; see research docs)</td><td>tennessean.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Nepal</th><td>— (no permitted public register; see research docs)</td><td>kathmandupost.com, ekantipur.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Netherlands</th><td>Eurofound ERM (EU-wide, daily)</td><td>nrc.nl, volkskrant.nl, fd.nl</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>New Caledonia</th><td>— (no permitted public register; see research docs)</td><td>lnc.nc</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>New Zealand</th><td>— (no permitted public register; see research docs)</td><td>nzherald.co.nz, rnz.co.nz, businessdesk.co.nz, stuff.co.nz, odt.co.nz, interest.co.nz</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Nicaragua</th><td>— (no permitted public register; see research docs)</td><td>laprensani.com, confidencial.digital</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Niger</th><td>— (no permitted public register; see research docs)</td><td>actuniger.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Nigeria</th><td>— (no permitted public register; see research docs)</td><td>premiumtimesng.com, punchng.com, businessday.ng, nairametrics.com, guardian.ng, thecable.ng, thisdaylive.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>North Korea</th><td>— (no permitted public register; see research docs)</td><td>nknews.org</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>North Macedonia</th><td>— (no permitted public register; see research docs)</td><td>slobodenpecat.mk, kapital.mk</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Northern Mariana Islands</th><td>— (no permitted public register; see research docs)</td><td>mvariety.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Norway</th><td>Eurofound ERM (EU-wide, daily)</td><td>aftenposten.no, e24.no, dn.no</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Oman</th><td>— (no permitted public register; see research docs)</td><td>timesofoman.com, muscatdaily.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Pakistan</th><td>— (no permitted public register; see research docs)</td><td>dawn.com, brecorder.com, tribune.com.pk</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Panama</th><td>— (no permitted public register; see research docs)</td><td>prensa.com, laestrella.com.pa</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Papua New Guinea</th><td>— (no permitted public register; see research docs)</td><td>postcourier.com.pg, thenational.com.pg</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Paraguay</th><td>— (no permitted public register; see research docs)</td><td>abc.com.py, ultimahora.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Peru</th><td>— (no permitted public register; see research docs)</td><td>elcomercio.pe, gestion.pe</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Philadelphia Inquirer</th><td>— (no permitted public register; see research docs)</td><td>inquirer.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Philippines</th><td>— (no permitted public register; see research docs)</td><td>inquirer.net, rappler.com, philstar.com, bworldonline.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Pittsburgh Post-Gazette</th><td>— (no permitted public register; see research docs)</td><td>post-gazette.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Poland</th><td>Eurofound ERM (EU-wide, daily)</td><td>notesfrompoland.com, pb.pl, rp.pl</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Portugal</th><td>Eurofound ERM (EU-wide, daily)</td><td>expresso.pt, publico.pt, jornaldenegocios.pt, eco.sapo.pt</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Puerto Rico</th><td>— (no permitted public register; see research docs)</td><td>elnuevodia.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Qatar</th><td>— (no permitted public register; see research docs)</td><td>gulf-times.com, thepeninsulaqatar.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Raleigh NC</th><td>— (no permitted public register; see research docs)</td><td>wral.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Romania</th><td>Eurofound ERM (EU-wide, daily)</td><td>zf.ro, adevarul.ro, g4media.ro</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Russia</th><td>— (no permitted public register; see research docs)</td><td>themoscowtimes.com, kyivindependent.com, kommersant.ru, rbc.ru, thebell.io</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Rwanda</th><td>— (no permitted public register; see research docs)</td><td>newtimes.co.rw</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Samoa</th><td>— (no permitted public register; see research docs)</td><td>samoaobserver.ws</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>San Diego</th><td>— (no permitted public register; see research docs)</td><td>sandiegouniontribune.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Saudi Arabia</th><td>— (no permitted public register; see research docs)</td><td>argaam.com, aleqt.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Senegal</th><td>— (no permitted public register; see research docs)</td><td>lequotidien.sn, enqueteplus.com, lesoleil.sn</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Serbia</th><td>— (no permitted public register; see research docs)</td><td>danas.rs, n1info.rs, novaekonomija.rs</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Seychelles</th><td>— (no permitted public register; see research docs)</td><td>seychellesnewsagency.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Sierra Leone</th><td>— (no permitted public register; see research docs)</td><td>awoko.org, thesierraleonetelegraph.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Singapore</th><td>— (no permitted public register; see research docs)</td><td>channelnewsasia.com, businesstimes.com.sg</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Slovakia</th><td>Eurofound ERM (EU-wide, daily)</td><td>sme.sk, hnonline.sk, dennikn.sk</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Slovenia</th><td>Eurofound ERM (EU-wide, daily)</td><td>delo.si, finance.si</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Solomon Islands</th><td>— (no permitted public register; see research docs)</td><td>solomonstarnews.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Somalia</th><td>— (no permitted public register; see research docs)</td><td>garoweonline.com, hiiraan.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>South Africa</th><td>— (no permitted public register; see research docs)</td><td>news24.com, businesslive.co.za, iol.co.za, moneyweb.co.za</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>South Korea</th><td>OpenDART discovery probe, 2×/day (list-only)</td><td>chosun.com, hankyung.com, koreaherald.com, koreatimes.co.kr, mk.co.kr</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>South Sudan</th><td>— (no permitted public register; see research docs)</td><td>radiotamazuj.org</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Spain</th><td>Eurofound ERM (EU-wide, daily)</td><td>elpais.com, expansion.com, elmundo.es, lavanguardia.com, eleconomista.es</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Sri Lanka</th><td>— (no permitted public register; see research docs)</td><td>ft.lk, economynext.com, dailymirror.lk</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>St. Louis Post-Dispatch</th><td>— (no permitted public register; see research docs)</td><td>stltoday.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>St. Lucia</th><td>— (no permitted public register; see research docs)</td><td>stluciatimes.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Sudan</th><td>— (no permitted public register; see research docs)</td><td>sudantribune.com, dabangasudan.org</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Suriname</th><td>— (no permitted public register; see research docs)</td><td>starnieuws.com, dwtonline.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Sweden</th><td>Eurofound ERM (EU-wide, daily)</td><td>dn.se, svd.se, di.se</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Switzerland</th><td>— (no permitted public register; see research docs)</td><td>swissinfo.ch, nzz.ch, letemps.ch, handelszeitung.ch</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Syria</th><td>— (no permitted public register; see research docs)</td><td>enabbaladi.net</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Taiwan</th><td>— (no permitted public register; see research docs)</td><td>taipeitimes.com, focustaiwan.tw, udn.com, digitimes.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Tampa Bay Times</th><td>— (no permitted public register; see research docs)</td><td>tampabay.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Tanzania</th><td>— (no permitted public register; see research docs)</td><td>thecitizen.co.tz, mwananchi.co.tz</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Thailand</th><td>— (no permitted public register; see research docs)</td><td>bangkokpost.com, nationthailand.com, bangkokbiznews.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>The Oregonian</th><td>— (no permitted public register; see research docs)</td><td>oregonlive.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Togo</th><td>— (no permitted public register; see research docs)</td><td>togofirst.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Tonga</th><td>— (no permitted public register; see research docs)</td><td>matangitonga.to</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Trinidad & Tobago</th><td>— (no permitted public register; see research docs)</td><td>guardian.co.tt, trinidadexpress.com, newsday.co.tt</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Tunisia</th><td>— (no permitted public register; see research docs)</td><td>businessnews.com.tn, lapresse.tn</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Turkey</th><td>— (no permitted public register; see research docs)</td><td>hurriyetdailynews.com, dailysabah.com, dunya.com, cumhuriyet.com.tr</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>UAE</th><td>— (no permitted public register; see research docs)</td><td>arabianbusiness.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>UK</th><td>— (no permitted public register; see research docs)</td><td>thetimes.co.uk, news.sky.com, standard.co.uk, cityam.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Uganda</th><td>— (no permitted public register; see research docs)</td><td>monitor.co.ug, newvision.co.ug</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Ukraine</th><td>— (no permitted public register; see research docs)</td><td>epravda.com.ua, pravda.com.ua, liga.net</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Uruguay</th><td>— (no permitted public register; see research docs)</td><td>elpais.com.uy, elobservador.com.uy</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Vanuatu</th><td>— (no permitted public register; see research docs)</td><td>dailypost.vu</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Venezuela</th><td>— (no permitted public register; see research docs)</td><td>elnacional.com, efectococuyo.com</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>Vietnam</th><td>— (no permitted public register; see research docs)</td><td>vnexpress.net, vietnamnews.vn, vneconomy.vn</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
<tr><th>United States & global English press</th><td>— (no permitted public register; see research docs)</td><td>thenationalnews.com, gulfnews.com, khaleejtimes.com, arabnews.com, thelocal.se, thelocal.de, thelocal.fr, startribune.com, chron.com, miamiherald.com, cnbc.com, thehill.com, healthcaredive.com, fiercepharma.com +32 more</td><td>Active · 2×/day (13:00 &amp; 22:00 UTC)</td></tr>
</tbody></table></div><p>Outlet scanning is allowlist-only: articles surface through GDELT's 65-language index and NewsAPI; sites are never crawled directly. Rotating country/state/industry queries sweep the full matrix every ~6–9 days on top of the broad twice-daily pull.</p></details>
