<?php
/**
 * GENERATED by railway/generate_warn_urls.py from
 * railway/sources/warn.py::STATE_WARN_URL. Do not edit by hand;
 * edit the Python map and re-run the generator (a parity test enforces it).
 *
 * Official state WARN program / database page per state. Used to show the
 * 'State WARN list' link beside a notice's exact-record link.
 */
if (!defined('ABSPATH')) exit;

function alt_state_warn_urls() {
    return array(
        'AK' => 'https://jobs.alaska.gov/RR/WARN_notices.htm',
        'AL' => 'https://workforce.alabama.gov/warn-list/',
        'AZ' => 'https://www.azjobconnection.gov/search/warn_lookups',
        'CA' => 'https://edd.ca.gov/siteassets/files/jobs_and_training/warn/warn_report1.xlsx',
        'CO' => 'https://cdle.colorado.gov/employers/layoff-separations/layoff-warn-list',
        'CT' => 'https://portal.ct.gov/dol/knowledge-base/articles/employment-and-training/rapid-response/warn',
        'DC' => 'https://does.dc.gov/page/industry-closings-and-layoffs-warn-notifications',
        'DE' => 'https://joblink.delaware.gov/search/warn_lookups',
        'FL' => 'https://reactwarn.floridajobs.org/WarnList/Records?year=2026',
        'GA' => 'https://www.tcsg.edu/warn-public-view/',
        'HI' => 'https://labor.hawaii.gov/wdc/real-time-warn-updates/',
        'IA' => 'https://workforce.iowa.gov/worker-adjustment-and-retraining-notification-act',
        'ID' => 'https://www.labor.idaho.gov/businesss/layoff-assistance/',
        'IL' => 'https://dceo.illinois.gov/workforcedevelopment/warn.html',
        'IN' => 'https://www.in.gov/dwd/warn-notices/',
        'KS' => 'https://www.kansasworks.com/search/warn_lookups',
        'KY' => 'https://kcc.ky.gov/employer/Pages/Business-Downsizing-Assistance---WARN.aspx',
        'LA' => 'https://www.laworks.net/Downloads/Downloads_WFD.asp',
        'MA' => 'https://www.mass.gov/info-details/worker-adjustment-and-retraining-notification-act-warn-layoff-and-closure-updates',
        'MD' => 'https://www.dllr.state.md.us/employment/warn.shtml',
        'ME' => 'https://joblink.maine.gov/search/warn_lookups',
        'MI' => 'https://www.michigan.gov/leo/bureaus-agencies/wd/data-public-notices/warn-notices',
        'MN' => 'https://mn.gov/deed/programs-services/dislocated-worker/employers/warn/',
        'MO' => 'https://jobs.mo.gov/warn',
        'MS' => 'https://mdes.ms.gov/information-center/warn-information/',
        'MT' => 'https://wsd.dli.mt.gov/wioa/related-links/warn-notice-page',
        'NC' => 'https://www.commerce.nc.gov/data-tools-reports/',
        'ND' => 'https://www.jobsnd.com/',
        'NE' => 'https://dol.nebraska.gov/ReemploymentServices/LayoffServices/LayoffsAndDownsizingWARN',
        'NJ' => 'https://www.nj.gov/labor/employer-services/warn/',
        'NM' => 'https://www.dws.state.nm.us/Rapid-Response',
        'NV' => 'https://detr.nv.gov/Page/WARN',
        'NY' => 'https://dol.ny.gov/warn-dashboard',
        'OH' => 'https://jfs.ohio.gov/job-services-and-unemployment/job-services/job-programs-and-services/submit-a-warn-notice/current-public-notices-of-layoffs-and-closures-sa/current-public-notices-of-layoffs-and-closures_warn',
        'OK' => 'https://www.employoklahoma.gov/Participants/s/warnnotices',
        'OR' => 'https://ccwd.hecc.oregon.gov/Layoff/WARN',
        'PA' => 'https://www.pa.gov/agencies/dli/programs-services/workforce-development-home/warn-requirements/warn-notices',
        'RI' => 'https://dlt.ri.gov/employers/worker-adjustment-and-retraining-notification-warn',
        'SC' => 'https://scworks.org/employer/employer-programs/risk-closing/layoff-notification-reports',
        'SD' => 'https://dlr.sd.gov/workforce_services/businesses/warn_notices.aspx',
        'TN' => 'https://www.tn.gov/workforce/general-resources/major-publications0/major-publications-redirect/reports.html',
        'TX' => 'https://www.twc.texas.gov/data-reports/warn-notice',
        'UT' => 'https://jobs.utah.gov/employer/business/warnnotices.html',
        'VA' => 'https://www.virginiaworks.gov/warn-notices',
        'VT' => 'https://www.vermontjoblink.com/search/warn_lookups',
        'WA' => 'https://esd.wa.gov/employer-requirements/layoffs-and-employee-notifications/worker-adjustment-and-retraining-notification-warn-layoff-and-closure-database',
        'WI' => 'https://dwd.wisconsin.gov/dislocatedworker/warn/',
        'WV' => 'https://workforcewv.org/job-seeker/layoffs-downsizing/warn-listing/',
    );
}

function alt_state_warn_list_url($state) {
    $map = alt_state_warn_urls();
    $state = strtoupper(trim((string) $state));
    return isset($map[$state]) ? $map[$state] : '';
}
