<?php
/**
 * GENERATED by railway/generate_warn_urls.py from
 * railway/sources/warn.py::STATE_WARN_URL. Do not edit by hand;
 * edit the Python map and re-run the generator (a parity test enforces it).
 *
 * Official state WARN program / database page per state. Used to show the
 * 'State WARN list' link beside a notice's exact-record link.
 */
if (!defined('ABSPATH')) exit;

function alt_state_warn_urls() {
    return array(
        'AK' => 'https://jobs.alaska.gov/RR/WARN_notices.htm',
        'AL' => 'https://www.madeinalabama.com/warn-list/',
        'AZ' => 'https://www.azcommerce.com/arizona-warn-notices',
        'CA' => 'https://edd.ca.gov/en/jobs_and_training/layoff_services_warn/',
        'CO' => 'https://cdle.colorado.gov/employers/layoff-separations/layoff-warn-list',
        'CT' => 'https://www.ctdol.state.ct.us/progsupt/bussrvce/warnreports/warnreports.htm',
        'DC' => 'https://does.dc.gov/page/industry-closings-and-layoffs-warn-notifications',
        'DE' => 'https://joblink.delaware.gov/search/warn_lookups',
        'FL' => 'https://floridajobs.org/workforce-resources/worker-adjustment-and-retraining-notification-(warn)',
        'GA' => 'https://www.dol.state.ga.us/public/es/warn/searchwarns/list',
        'HI' => 'https://labor.hawaii.gov/wdc/warn-notices/',
        'IA' => 'https://www.iowaworkforcedevelopment.gov/worker-adjustment-and-retraining-notification-act',
        'ID' => 'https://www.labor.idaho.gov/businesss/layoff-assistance/',
        'IL' => 'https://dceo.illinois.gov/workforcedevelopment/warn.html',
        'IN' => 'https://www.in.gov/dwd/warn-notices/',
        'KS' => 'https://www.kansasworks.com/search/warn_lookups',
        'KY' => 'https://kcc.ky.gov/employer/Pages/Business-Downsizing-Assistance---WARN.aspx',
        'LA' => 'https://www.laworks.net/Downloads/Downloads_WFD.asp',
        'MA' => 'https://www.mass.gov/info-details/worker-adjustment-and-retraining-notification-act-warn-layoff-and-closure-updates',
        'MD' => 'https://www.dllr.state.md.us/employment/warn.shtml',
        'ME' => 'https://joblink.maine.gov/search/warn_lookups',
        'MI' => 'https://milmi.org/warn/',
        'MO' => 'https://jobs.mo.gov/warn',
        'MT' => 'https://wsd.dli.mt.gov/wioa/related-links/warn-notice-page',
        'NE' => 'https://dol.nebraska.gov/ReemploymentServices/LayoffServices/LayoffsAndDownsizingWARN',
        'NJ' => 'https://www.nj.gov/labor/employer-services/warn/',
        'NM' => 'https://www.dws.state.nm.us/Rapid-Response',
        'NY' => 'https://dol.ny.gov/warn-notices',
        'OH' => 'https://jfs.ohio.gov/warn/index.stm',
        'OK' => 'https://oklahoma.gov/oesc/businesses/warn-notices.html',
        'OR' => 'https://ccwd.hecc.oregon.gov/Layoff/WARN',
        'PA' => 'https://www.pa.gov/en/agencies/dli/programs-services/workforce-development/warn.html',
        'RI' => 'https://dlt.ri.gov/employers/worker-adjustment-and-retraining-notification-warn',
        'SC' => 'https://scworks.org/employer/employer-programs/at-risk-of-closing/layoff-notification-reports',
        'SD' => 'https://dlr.sd.gov/workforce_services/businesses/warn_notices.aspx',
        'TN' => 'https://www.tn.gov/workforce/general-resources/major-publications0/major-publications-redirect/reports.html',
        'TX' => 'https://www.twc.texas.gov/programs/rapid-response-program',
        'UT' => 'https://jobs.utah.gov/employer/business/warnnotices.html',
        'VA' => 'https://www.vec.virginia.gov/warn-notices',
        'VT' => 'https://www.vermontjoblink.com/search/warn_lookups',
        'WA' => 'https://esd.wa.gov/employer-requirements/layoffs-and-employee-notifications/worker-adjustment-and-retraining-notification-warn-layoff-and-closure-database',
        'WI' => 'https://dwd.wisconsin.gov/dislocatedworker/warn/',
    );
}

function alt_state_warn_list_url($state) {
    $map = alt_state_warn_urls();
    $state = strtoupper(trim((string) $state));
    return isset($map[$state]) ? $map[$state] : '';
}
